backend:
  name: github
  repo: betagouv/andi
  branch: poc_netlify_cms

site_url: https://andi.beta.gouv.fr
display_url: https://andi.beta.gouv.fr

media_folder: static/assets
public_folder: assets

collections:
  - name: 'pages'
    label: 'Pages'
    files:
        - label: "Page d'accueil"
          name: "landing page"
          file: "contents/index.yml"
          fields:
            - { name: 'hero_title  ', label: 'Titre', widget: 'text'}
            - { name: 'hero_subtitle', label: 'Sous-titre', widget: 'text'}
            - { name: 'hero_button', label: 'Permier Bouton', widget: 'string'}
  # - name: blog
  #   label: Blog
  #   folder: blog
  #   create: true
  #   fields:
  #     - { name: path, label: Path }
  #     - { name: date, label: Date, widget: date }
  #     - { name: title, label: Title }
  #     - { name: body, label: Body, widget: markdown }
