---
- hosts: all
  vars:
    intendant_password: [INTENDANT_PASSWORD]
    jupyter_password: [JUPYTER_PASSWORD]
  tasks:

  ## Database creation
  - name: add default database
    postgresql_db:
        name: andi
        encoding: UTF-8

  ## User setup
  - name: add default user
    postgresql_user:
        db: andi
        name: intendant
        password: "{{ intendant_password }}"
        role_attr_flags: CREATEDB,LOGIN,SUPERUSER
        priv: "CONNECT"

  - name: add jupyter user
    postgresql_user:
        db: andi
        name: jupyter
        password: "{{ jupyter_password }}"
        role_attr_flags: LOGIN
        priv: "CONNECT"

  - name: allow default user connecting through tunnel
    postgresql_pg_hba:
        dest: /etc/postgresql/12/main/pg_hba.conf
        contype: host
        users: intendant,jupyter
        databases: andi
        source: [HOST IP]
        method: password

  ## Extensions
  - name: activate postgis
    postgresql_ext:
        name: postgis
        db: andi

  - name: activate cube
    postgresql_ext:
        name: cube
        db: andi

  - name: activate earthdistance
    postgresql_ext:
        name: earthdistance
        db: andi

  - name: activate earthdistance
    postgresql_ext:
        name: pg_trgm
        db: andi
